name: On tags

on:
  push:
    tags:
      - *

jobs:
  push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm set registry "https://npmjs.com"
          npm set //npmjs.com/:_authToken="${{NPM_TOKEN}}"
          npm install
          npm version ${{ steps.get_version.outputs.VERSION }}
          npm publish
